### ISSUE TITLE
Missing conditional

### ISSUE THREAD

**Issue by Baughn** [Fatmice/Uranium-Power-Cont#1]
Hi,

I had a look at control.lua after Liquius told me you're taking over, and it looks like there's a glitch in your import. If you look at https://github.com/Fatmice/Uranium-Power-Cont/blob/master/control.lua#L166, the conditional that's commented out is necessary for the fuel assemblies to degrade over time at all; as-is, you're continuously setting them to full health.

(Which is a scale of 0-1, by the way. 10 is over the top.)

**Comment by Fatmice** [comment]
Hi,
I have local copy of your code.  I liked how you used the .health.  I had no idea that .health could be used on items.  I've reverted part of your changes back Liquius and will adapt your additions soon.

The game always initialized item.health as 1 and never more than 1.  10 was to see if a number higher than 1 would work.  There was also some other experiments that I was doing that necessitate halting fuel decay.

The current code has no fuel decay yet but will soon.  I have to implement that at the same time as reprocessing.
