### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by hAh0L13** [Fatmice/Uranium-Power-Cont#13]
Hello

I'd copy master branch via zip archive and install manually C:\Users\%username%\AppData\Roaming\Factorio\mods\

When i'd start Factorio, it tells me that can't open file UraniumPower_0.6.4\graphics/entity/explosions/uranium-explosion-1.png on loading sprites (40%) stage.

Win7 x64, Factorio 0.13.13 x64

**Comment by Fatmice** [comment]
Issue has been fixed.
