### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by npo6ka** [Fatmice/Uranium-Power-Cont#17]
(I'm sorry for bad my english)
I play modpack Farlands v0.13.1 and I want to get the uranium energy, but when I put the 4.7% uranium rod in the reactor 72MV Fession Access port the game crashes
Uranium-Power v6.4 and v6.5 behave the same...

Error while running event on_tick (ID 0)
**UraniumPower**/controls.lua:354: attempt to index fiels '?' (a nil value)

![default](https://cloud.githubusercontent.com/assets/13215491/18692775/3da392b6-7fa5-11e6-9ff5-3328797b9777.png)

**Comment by npo6ka** [comment]
I'm fixed it.
added condiition in function "calculate_fuel_amount()"

for assemblyType, count in pairs(chest.get_contents()) do
 item = fuelAssemblyPotential[assemblyType]
  if (item ~= nil) then
  reactorChestPotential = reactorChestPotential + (item[1] \* count)
 end
end

**Comment by Fatmice** [comment]
Fixed in commit 65070de82a35db502661c9024562c8e50c69af74
