### ISSUE TITLE
graphics/entity/explosions/uranium-explosion-1.png is corrupt

### ISSUE THREAD

**Issue by epsilon-phase** [Fatmice/Uranium-Power-Cont#9]
The existing graphic for the uranium explosion is broken, it seems to simply be corrupt. It'd be great if you could fix it(by reverting it to the previous version, which does work).

**Comment by Fatmice** [comment]
Silently fixed and have been reuploaded on forum and mod portal.

**Comment by epsilon-phase** [comment]
Thank you, I noticed that you closed it, and it had disappeared when I ran
factorio again on a different machine.
